add hcio to syncoid

diff --git a/syncoid-job b/syncoid-job
--- a/syncoid-job
+++ b/syncoid-job
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+# fail hcio if anything goes wrong
+set -e
+
+# hcio start
+curl https://hc-ping.com/uWDfVXr2W4O9rF7deuOEog/syncoid/start
+
 echo "Syncing nic@ghost:tank/encrypted!" >> /home/nic/mycron.log
 syncoid --no-sync-snap --sendoptions=w --no-privilege-elevation nic@ghost:tank/encrypted tank/encrypted
 
@@ -22,3 +28,6 @@ syncoid --no-sync-snap --sendoptions=w --no-privilege-elevation nic@ghost:tank/e
 
 echo "Syncing nic@ghost:tank/encrypted/docker!" >> /home/nic/mycron.log
 syncoid --no-sync-snap --sendoptions=w --no-privilege-elevation nic@ghost:tank/encrypted/docker tank/encrypted/docker
+
+# hcio
+curl -m 10 --retry 5 https://hc-ping.com/uWDfVXr2W4O9rF7deuOEog/syncoid
